@startuml

participant "User" as user
participant "Post Service" as postserv
participant "Automoderator" as automod
participant "Notification Service" as notserv
participant "Post Database" as postdb

user -> postserv: Transmit new comment
activate postserv

postserv -> automod: Submit for moderation
activate automod
automod --> postserv
deactivate automod

postserv -> postdb: Transmit new comment details


postserv -> notserv: Inform of new comment event

deactivate postserv

@enduml
