@startuml

participant "User" as user
participant "Automoderator" as automod
participant "Moderation Service" as modserv
participant "Post Service" as postserv
participant "Notification Service" as notserv
participant "Moderation Database" as db

automod -> modserv: Inform of objectionable post
activate modserv

modserv -> postserv: Command to hide post

activate postserv

postserv -> postserv: Hide post

postserv --> modserv

modserv -> db: Add post to mod queue

modserv -> notserv: Command to notify user
deactivate modserv

activate notserv

notserv -> user: Notification of moderation action to user who made post

deactivate notserv

deactivate postserv


@enduml
