@startuml
participant "Moderator" as mod
participant "Moderation Service" as modserv
participant "Notification Service" as notserv
participant "Account Service" as accserv
participant "User" as user
participant "Moderation Database" as db
participant "Post Service" as post

mod -> db: Request a post from the queue
activate db
db --> mod: Return a post to review
deactivate db



mod -> modserv: Indicate if the post is ok or not
activate modserv

alt the post is objectionable

modserv -> notserv: Command to send notification to user
activate notserv
notserv -> user: Notify of flagged post
deactivate notserv

modserv -> accserv: Increment removed post count

activate accserv

opt user has 5 or more flagged posts

accserv -> accserv: Ban user
accserv -> notserv: Command to send notification to user
activate notserv
notserv -> user: Notify of ban
deactivate notserv

end

deactivate accserv

modserv -> post: Command to make post visible again


end

deactivate modserv
@enduml
